ALTER TABLE arenas ADD COLUMN shown TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE kits ADD COLUMN shown TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE game_modes ADD COLUMN shown TINYINT(1) NOT NULL DEFAULT 1;
